In [1]:
#Importing Libraries

In [2]:
import numpy as np
import math

In [3]:
#Sigmoid function

In [4]:
def sigmoid(x):
    return 1/(1+math.exp(-1))

In [5]:
#Derivative of sigmoid function

In [6]:
def derivative_sigmoid(y):
    derivative = sigmoid(y)*(1-sigmoid(y))
    return derivative

In [7]:
print(derivative_sigmoid(1))

0.19661193324148185


In [8]:
#Initializing Input Variables(X) and output variable(Y)

In [9]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
Y=np.array([[1],[1],[0]])

In [10]:
#Initializing Weights and biases with random values

In [11]:
Wh=np.random.rand(4,3)
wout=np.random.rand(3,1)
bh=np.random.rand(1,3)
bout=np.random.rand(1,1)

In [12]:
#calculate hidden layer input

In [13]:
hidden_layer_input = np.dot(X,Wh)+bh
print(hidden_layer_input)

[[1.0754419  1.43227908 1.30226096]
 [1.61345261 1.81562111 1.72913451]
 [1.54470524 1.41220409 1.79992098]]


In [14]:
#performing nonlinear activation on hidden linear input(using sigmoid function)

In [15]:
hidden_layer_activation=np.vectorize(sigmoid)(hidden_layer_input)
print(hidden_layer_activation)

[[0.73105858 0.73105858 0.73105858]
 [0.73105858 0.73105858 0.73105858]
 [0.73105858 0.73105858 0.73105858]]


In [16]:
#perform linear and nonlinear transformation of hidden layer at output layer

In [17]:
output_layer_input = np.dot(hidden_layer_activation,wout)+bout
output = np.vectorize(sigmoid)(output_layer_input)
print(output_layer_input)
print(output)

[[1.32044819]
 [1.32044819]
 [1.32044819]]
[[0.73105858]
 [0.73105858]
 [0.73105858]]


In [ ]:
#calculate the gradient of error at output layer


In [29]:
Error = Y-output
print(Error)

[[ 0.26894142]
 [ 0.26894142]
 [-0.73105858]]


In [ ]:
#compute slope at output and hidden layer

In [18]:
slope_output_layer = np.vectorize(derivative_sigmoid)(output)
slope_hidden_layer= np.vectorize(derivative_sigmoid)(hidden_layer_activation)
print(slope_output_layer)
print(slope_hidden_layer)

[[0.19661193]
 [0.19661193]
 [0.19661193]]
[[0.19661193 0.19661193 0.19661193]
 [0.19661193 0.19661193 0.19661193]
 [0.19661193 0.19661193 0.19661193]]


In [ ]:
#compute delta at output layer

In [42]:
lr=0.1
d_output = Error*slope_output_layer*lr
print(d_output)

[[ 0.00528771]
 [ 0.00528771]
 [-0.01437348]]


In [ ]:
#calculate Error at hidden layer

In [48]:
wout_transpose = np.transpose(wout)
Error_hidden_layer=np.dot(d_output, wout_transpose)
print(Error_hidden_layer)

[[ 0.00480439  0.00170291  0.00042824]
 [ 0.00480439  0.00170291  0.00042824]
 [-0.0130597  -0.00462899 -0.00116408]]


In [ ]:
#compute delta hidden layer

In [50]:
d_hidden_layer = Error_hidden_layer * slope_hidden_layer
print(d_hidden_layer)

[[ 9.44601203e-04  3.34812353e-04  8.41969641e-05]
 [ 9.44601203e-04  3.34812353e-04  8.41969641e-05]
 [-2.56769229e-03 -9.10114334e-04 -2.28871077e-04]]


In [ ]:
#update weight at both output and hidden layer

In [57]:
hidden_layer_activation_transpose=np.transpose(hidden_layer_activation)
wout=wout+np.dot(hidden_layer_activation_transpose, d_output) *lr 
print(wout)
X_transpose = np.transpose(X)
Wh = Wh + np.dot(X_transpose, d_hidden_layer) *lr 
print(Wh)

[[0.90720818]
 [0.32066223]
 [0.07959938]]
[[0.58500633 0.48046558 0.45942822]
 [0.03915138 0.68546424 0.15495065]
 [0.60235979 0.0244198  0.09786535]
 [0.22234754 0.81890592 0.42332969]]


In [ ]:
#update biases at both output and hidden layer

In [61]:
bh = bh + np.sum(d_hidden_layer, axis=0)*lr
bout=bout+ np.sum(d_output, axis=0)*lr
print(bh,bout)

[[0.35366888 0.55228632 0.11738816]] [[0.68777299]]
