In [1]:
#Importing Libraries

In [2]:
import numpy as np
import math

In [3]:
#Sigmoid function

In [4]:
#Derivative of sigmoid function

In [5]:
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [6]:
print(sigmoid(1.641))

0.837670961661056


In [7]:
def derivative_sigmoid(y):
    derivative = sigmoid(y)*(1-sigmoid(y))
    return derivative

In [8]:
print(derivative_sigmoid(1))

0.19661193324148185


In [9]:
#Initializing Input Variables(X) and output variable(Y)

In [10]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
Y=np.array([[1],[1],[0]])

In [11]:
#Initializing Weights and biases with random values

In [12]:
Wh=np.random.rand(4,3)
wout=np.random.rand(3,1)
bh=np.random.rand(1,3)
bout=np.random.rand(1,1)

In [13]:
print(Wh, wout, bh, bout)

[[0.71817708 0.24764411 0.36550635]
 [0.94962446 0.57473399 0.47573953]
 [0.19689343 0.34183847 0.24020238]
 [0.53210625 0.02133086 0.90207725]] [[0.47785142]
 [0.99272226]
 [0.37348051]] [[0.34308152 0.60987843 0.54084847]] [[0.89959675]]


In [18]:
#calculate hidden layer input

In [14]:
hidden_layer_input = np.dot(X,Wh)+bh
print(hidden_layer_input)

[[1.25815203 1.199361   1.14655719]
 [1.79025828 1.22069186 2.04863444]
 [1.82481223 1.20594328 1.91866525]]


In [21]:
#performing nonlinear activation on hidden linear input(using sigmoid function)

In [15]:
hidden_layer_activation=np.vectorize(sigmoid)(hidden_layer_input)
print(hidden_layer_activation)

[[0.77870783 0.76841109 0.75888151]
 [0.85695894 0.77218528 0.88580956]
 [0.86114256 0.76958037 0.87198952]]


In [23]:
#perform linear and nonlinear transformation of hidden layer at output layer

In [16]:
output_layer_input = np.dot(hidden_layer_activation,wout)+bout
output = np.vectorize(sigmoid)(output_layer_input)
print(output_layer_input)
print(output)

[[2.31794964]
 [2.40649392]
 [2.4007456 ]]
[[0.91035275]
 [0.91732116]
 [0.91688414]]


In [25]:
#calculate the gradient of error at output layer


In [17]:
Error = Y-output
print(Error)

[[ 0.08964725]
 [ 0.08267884]
 [-0.91688414]]


In [27]:
#compute slope at output and hidden layer

In [18]:
slope_output_layer = np.vectorize(derivative_sigmoid)(output)
slope_hidden_layer= np.vectorize(derivative_sigmoid)(hidden_layer_activation)
print(slope_output_layer)
print(slope_hidden_layer)

[[0.20460018]
 [0.20399148]
 [0.20402972]]
[[0.21562626 0.21644616 0.21719886]
 [0.20918594 0.21614642 0.20672574]
 [0.20883187 0.21635339 0.20790958]]


In [19]:
#compute delta at output layer

In [20]:
lr=0.1
d_output = Error*slope_output_layer*lr
print(d_output)

[[ 0.00183418]
 [ 0.00168658]
 [-0.01870716]]


In [31]:
#calculate Error at hidden layer

In [21]:
wout_transpose = np.transpose(wout)
Error_hidden_layer=np.dot(d_output, wout_transpose)
print(Error_hidden_layer)

[[ 0.00087647  0.00182084  0.00068503]
 [ 0.00080593  0.0016743   0.0006299 ]
 [-0.00893924 -0.01857102 -0.00698676]]


In [33]:
#compute delta hidden layer

In [22]:
d_hidden_layer = Error_hidden_layer * slope_hidden_layer
print(d_hidden_layer)

[[ 0.00018899  0.00039411  0.00014879]
 [ 0.00016859  0.00036189  0.00013022]
 [-0.0018668  -0.0040179  -0.00145261]]


In [35]:
#update weight at both output and hidden layer

In [23]:
hidden_layer_activation_transpose=np.transpose(hidden_layer_activation)
wout=wout+np.dot(hidden_layer_activation_transpose, d_output) *lr 
print(wout)
X_transpose = np.transpose(X)
Wh = Wh + np.dot(X_transpose, d_hidden_layer) *lr 
print(Wh)

[[0.47652782]
 [0.99155377]
 [0.37213786]]
[[0.71821284 0.24771971 0.36553425]
 [0.94943778 0.5743322  0.47559427]
 [0.19692919 0.34191407 0.24023028]
 [0.53193643 0.02096526 0.90194501]]


In [37]:
#update biases at both output and hidden layer

In [24]:
bh = bh + np.sum(d_hidden_layer, axis=0)*lr
bout=bout+ np.sum(d_output, axis=0)*lr
print(bh,bout)

[[0.3429306  0.60955224 0.54073111]] [[0.89807811]]
